import 'dart:io';

void main() {
  final file = File('lib/main.dart');
  final lines = file.readAsLinesSync();

  int startIndex = -1;
  int endIndex = -1;

  for (int i = 0; i < lines.length; i++) {
    if (lines[i].contains('void initState() {')) {
      startIndex = i;
    }
    if (startIndex != -1 && lines[i].contains('_pageController = PageController();')) {
      endIndex = i;
      break;
    }
  }

  if (startIndex != -1 && endIndex != -1) {
    final newInitState = [
      '  @override',
      '  void initState() {',
      '    super.initState();',
      '    _allPosts = [',
      '      PostData(',
      "        id: '1',",
      "        title: '오늘의 데이트 룩, 뭐가 더 심쿵해?',",
      "        uploaderId: '@style_guru',",
      "        uploaderImage: 'assets/profiles/profile_11.jpg',",
      "        timeLocation: '서울 강남구 • 2시간 전',",
      "        imageA: 'assets/images/post1_a.jpg',",
      "        imageB: 'assets/images/post1_b.jpg',",
      "        descriptionA: '트렌디한 오버사이즈 핏과 미니멀한 블랙 코디의 정석',",
      "        descriptionB: '화려한 패턴과 유니크한 액세서리로 완성된 힙스터 룩',",
      '        likesCount: 1200,',
      '        commentsCount: 342,',
      "        voteCountA: '1.2k',",
      "        voteCountB: '800',",
      "        percentA: '60%',",
      "        percentB: '40%',",
      '        isFollowing: true,',
      '        isBookmarked: false,',
      '        totalVotes: 2000,',
      '        remainingSeconds: 3600,',
      '      ),',
      '      PostData(',
      "        id: '2',",
      "        title: '출근룩 이거 어떰?',",
      "        uploaderId: '@office_worker',",
      "        uploaderImage: 'assets/profiles/profile_32.jpg',",
      "        timeLocation: '판교 • 5시간 전',",
      "        imageA: 'assets/images/post2_a.jpg',",
      "        imageB: 'assets/images/post2_b.jpg',",
      "        descriptionA: '깔끔한 셔츠와 슬랙스 조합, 신뢰감을 주는 비즈니스 캐주얼',",
      "        descriptionB: '편안한 니트와 베이지 면바지, 다정하고 부드러운 오피스 룩',",
      '        likesCount: 850,',
      '        commentsCount: 120,',
      "        voteCountA: '450',",
      "        voteCountB: '400',",
      "        percentA: '53%',",
      "        percentB: '47%',",
      '        isFollowing: false,',
      '        isBookmarked: true,',
      '        totalVotes: 850,',
      '        remainingSeconds: 7200,',
      '      ),',
      '      PostData(',
      "        id: '3',",
      "        title: '휴양지 패션 추천좀!',",
      "        uploaderId: '@traveler_j',",
      "        uploaderImage: 'assets/profiles/profile_44.jpg',",
      "        timeLocation: '제주도 • 1일 전',",
      "        imageA: 'assets/images/post3_a.jpg',",
      "        imageB: 'assets/images/post3_b.jpg',",
      "        descriptionA: '시원한 리넨 셔츠와 반바지, 휴양지의 여유가 느껴지는 스타일',",
      "        descriptionB: '에스닉한 무드와 로브로 인생샷을 부르는 화려한 바캉스 룩',",
      '        likesCount: 2500,',
      '        commentsCount: 890,',
      "        voteCountA: '1.8k',",
      "        voteCountB: '700',",
      "        percentA: '72%',",
      "        percentB: '28%',",
      '        isFollowing: true,',
      '        isBookmarked: true,',
      '        totalVotes: 2500,',
      '        remainingSeconds: 1800,',
      '      ),',
      '      PostData(',
      "        id: '4',",
      "        title: '운동복 뭐가 나을까?',",
      "        uploaderId: '@gym_rat',",
      "        uploaderImage: 'assets/profiles/profile_12.jpg',",
      "        timeLocation: '부산 • 3시간 전',",
      "        imageA: 'assets/images/post4_a.jpg',",
      "        imageB: 'assets/images/post4_b.jpg',",
      "        descriptionA: '기능성에 집중한 컴프레션 웨어, 운동 효율을 높여주는 복장',",
      "        descriptionB: '트렌디한 디자인의 조거 팬츠와 후드, 짐웨어로도 일상복으로도 만점',",
      '        likesCount: 500,',
      '        commentsCount: 40,',
      "        voteCountA: '300',",
      "        voteCountB: '200',",
      "        percentA: '60%',",
      "        percentB: '40%',",
      '        isFollowing: false,',
      '        isBookmarked: false,',
      '        totalVotes: 500,',
      '        remainingSeconds: 86400,',
      '      ),',
      '      PostData(',
      "        id: '5',",
      "        title: '오늘 저녁 뭐 먹지?',",
      "        uploaderId: '@foodie_kim',",
      "        uploaderImage: 'assets/profiles/profile_60.jpg',",
      "        timeLocation: '홍대 • 10분 전',",
      "        imageA: 'assets/images/post5_a.jpg',",
      "        imageB: 'assets/images/post5_b.jpg',",
      "        descriptionA: '매콤한 감칠맛이 일품인 전통 한식 메뉴, 한국인의 소울 푸드',",
      "        descriptionB: '치즈가 듬뿍 들어간 정통 이탈리안 파스타, 특별한 날에 어울리는 맛',",
      '        likesCount: 3000,',
      '        commentsCount: 1200,',
      "        voteCountA: '2k',",
      "        voteCountB: '1k',",
      "        percentA: '67%',",
      "        percentB: '33%',",
      '        isFollowing: true,',
      '        isBookmarked: false,',
      '        totalVotes: 3000,',
      '        remainingSeconds: 600,',
      '      ),',
      '      PostData(',
      "        id: '6',",
      "        title: '스마트폰 케이스 골라줘',",
      "        uploaderId: '@tech_nerd',",
      "        uploaderImage: 'assets/profiles/profile_68.jpg',",
      "        timeLocation: '용산 • 12시간 전',",
      "        imageA: 'assets/images/post6_a.jpg',",
      "        imageB: 'assets/images/post6_b.jpg',",
      "        descriptionA: '애플 로고가 돋보이는 투명 실리콘 케이스, 기기 본연의 디자인 강조',",
      "        descriptionB: '강력한 보호 성능의 터프 케이스, 내구성과 스포티한 감성',",
      '        likesCount: 200,',
      '        commentsCount: 15,',
      "        voteCountA: '100',",
      "        voteCountB: '100',",
      "        percentA: '50%',",
      "        percentB: '50%',",
      '        isFollowing: false,',
      '        isBookmarked: true,',
      '        totalVotes: 200,',
      '        remainingSeconds: 43200,',
      '      ),',
      '      PostData(',
      "        id: '7',",
      "        title: '신혼여행 어디가 좋아?',",
      "        uploaderId: '@bride_to_be',",
      "        uploaderImage: 'assets/profiles/profile_5.jpg',",
      "        timeLocation: '강남 • 1주일 전',",
      "        imageA: 'assets/images/post7_a.jpg',",
      "        imageB: 'assets/images/post7_b.jpg',",
      "        descriptionA: '투명한 바다와 럭셔리 풀빌라가 있는 몰디브, 꿈같은 휴식',",
      "        descriptionB: '유서 깊은 건축물과 예술적 향기 가득한 유럽, 낭만적인 도시 여행',",
      '        likesCount: 15000,',
      '        commentsCount: 2300,',
      "        voteCountA: '8.2k',",
      "        voteCountB: '6.8k',",
      "        percentA: '55%',",
      "        percentB: '45%',",
      '        isFollowing: false,',
      '        isBookmarked: false,',
      '        totalVotes: 15000,',
      '        remainingSeconds: 0,',
      '      ),',
      '      PostData(',
      "        id: '8',",
      "        title: '치킨 vs 피자, 평생 하나만 먹는다면?',",
      "        uploaderId: '@food_master',",
      "        uploaderImage: 'assets/profiles/profile_15.jpg',",
      "        timeLocation: '전국 • 3일 전',",
      "        imageA: 'assets/images/post8_a.jpg',",
      "        imageB: 'assets/images/post8_b.jpg',",
      "        descriptionA: '바삭한 튀김옷과 육즙 가득한 치킨, 야식계의 영원한 1인자',",
      "        descriptionB: '다양한 토핑과 쫄깃한 도우의 조화, 파티에 빠질 수 없는 피자',",
      '        likesCount: 25000,',
      '        commentsCount: 5400,',
      "        voteCountA: '14k',",
      "        voteCountB: '11k',",
      "        percentA: '56%',",
      "        percentB: '44%',",
      '        isFollowing: false,',
      '        isBookmarked: true,',
      '        totalVotes: 25000,',
      '        remainingSeconds: 0,',
      '      ),',
      '      PostData(',
      "        id: '9',",
      "        title: '여름 휴가는 바다? 계곡?',",
      "        uploaderId: '@vacation_king',",
      "        uploaderImage: 'assets/profiles/profile_20.jpg',",
      "        timeLocation: '강원도 • 4일 전',",
      "        imageA: 'assets/images/post9_a.jpg',",
      "        imageB: 'assets/images/post9_b.jpg',",
      "        descriptionA: '끝없이 펼쳐진 수평선과 파도 소리, 가슴이 뻥 뚫리는 푸른 바다',",
      "        descriptionB: '울창한 숲과 차가운 계곡물, 자연 속에서 즐기는 시원한 휴식',",
      '        likesCount: 12000,',
      '        commentsCount: 1100,',
      "        voteCountA: '5k',",
      "        voteCountB: '7k',",
      "        percentA: '42%',",
      "        percentB: '58%',",
      '        isFollowing: false,',
      '        isBookmarked: false,',
      '        totalVotes: 12000,',
      '        remainingSeconds: 0,',
      '      ),',
      '      PostData(',
      "        id: '10',",
      "        title: '갤럭시 vs 아이폰',",
      "        uploaderId: '@tech_reviewer',",
      "        uploaderImage: 'assets/profiles/profile_35.jpg',",
      "        timeLocation: '서울 • 10일 전',",
      "        imageA: 'assets/images/post10_a.jpg',",
      "        imageB: 'assets/images/post10_b.jpg',",
      "        descriptionA: '극한의 커스터마이징과 편리한 기능들, 자유도가 높은 갤럭시',",
      "        descriptionB: '매끄러운 사용자 경험과 감각적인 디자인, 생태계가 강력한 아이폰',",
      '        likesCount: 50000,',
      '        commentsCount: 15000,',
      "        voteCountA: '23k',",
      "        voteCountB: '27k',",
      "        percentA: '46%',",
      "        percentB: '54%',",
      '        isFollowing: true,',
      '        isBookmarked: false,',
      '        totalVotes: 50000,',
      '        remainingSeconds: 0,',
      '      ),',
      '    ];',
      '    _filteredPosts = List.from(_allPosts);',
    ];

    lines.replaceRange(startIndex, endIndex, newInitState);
    file.writeAsStringSync(lines.join('\n'));
    print('Fixed initState and post data.');
  } else {
    print('Could not find initState or pageController.');
  }
}
