import 'dart:io';

void main() {
  final file = File('lib/main.dart');
  final lines = file.readAsLinesSync();

  // MEGA FIX: Replace entire sections that are known to be problematic.
  
  // 1. Fix PointScreen class (Lines 1850-2100 approx)
  int pointScreenStart = -1;
  int pointScreenEnd = -1;
  for (int i = 0; i < lines.length; i++) {
    if (lines[i].contains('class PointScreen extends StatefulWidget')) {
      pointScreenStart = i;
    }
    if (pointScreenStart != -1 && lines[i].contains('class StoreScreen extends StatefulWidget')) {
      pointScreenEnd = i;
      break;
    }
  }
  
  if (pointScreenStart != -1 && pointScreenEnd != -1) {
    print('Replacing PointScreen class...');
    final newPointScreen = [
      'class PointScreen extends StatefulWidget {',
      '  final int currentPoints;',
      '  const PointScreen({super.key, required this.currentPoints});',
      '',
      '  @override',
      '  State<PointScreen> createState() => _PointScreenState();',
      '}',
      '',
      'class _PointScreenState extends State<PointScreen> {',
      '  late int _userPoints;',
      '  final List<PointHistoryItem> _history = [',
      "    PointHistoryItem(title: '친구 초대 보상', amount: 500, date: '1일 전', isEarned: true),",
      "    PointHistoryItem(title: '광고 시청 보상', amount: 50, date: '2일 전', isEarned: true),",
      "    PointHistoryItem(title: '상품권 교환', amount: 5000, date: '3일 전', isEarned: false),",
      "    PointHistoryItem(title: '투표 참여 보상', amount: 10, date: '4일 전', isEarned: true),",
      '  ];',
      '',
      '  @override',
      '  void initState() {',
      '    super.initState();',
      '    _userPoints = widget.currentPoints;',
      '  }',
      '',
      '  @override',
      '  Widget build(BuildContext context) {',
      '    return Scaffold(',
      '      backgroundColor: Colors.black,',
      '      appBar: AppBar(',
      '        backgroundColor: Colors.black,',
      '        elevation: 0,',
      '        leading: IconButton(',
      '          icon: const Icon(Icons.arrow_back_ios, color: Colors.white),',
      '          onPressed: () => Navigator.pop(context),',
      '        ),',
      "        title: const Text('나의 포인트', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),",
      '        centerTitle: true,',
      '      ),',
      '      body: SingleChildScrollView(',
      '        padding: const EdgeInsets.all(20),',
      '        child: Column(',
      '          crossAxisAlignment: CrossAxisAlignment.start,',
      '          children: [',
      '            Container(',
      '              width: double.infinity,',
      '              padding: const EdgeInsets.all(24),',
      '              decoration: BoxDecoration(',
      '                gradient: const LinearGradient(',
      '                  colors: [Color(0xFF2C2C2C), Color(0xFF1C1C1C)],',
      '                  begin: Alignment.topLeft,',
      '                  end: Alignment.bottomRight,',
      '                ),',
      '                borderRadius: BorderRadius.circular(24),',
      '                border: Border.all(color: Colors.white.withOpacity(0.05)),',
      '              ),',
      '              child: Column(',
      '                crossAxisAlignment: CrossAxisAlignment.start,',
      '                children: [',
      "                  const Text('나의 보유 포인트', style: TextStyle(color: Colors.white70, fontSize: 14)),",
      '                  const SizedBox(height: 12),',
      '                  Row(',
      '                    children: [',
      "                      const Text('P', style: TextStyle(color: Colors.cyanAccent, fontSize: 28, fontWeight: FontWeight.bold)),",
      '                      const SizedBox(width: 10),',
      '                      Text(',
      '                        _userPoints.toString().replaceAllMapped(RegExp(r"(\\d{1,3})(?=(\\d{3})+(?!\\d))"), (Match m) => "\${m[1]},"),',
      "                        style: const TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.w900, letterSpacing: -0.5),",
      '                      ),',
      '                    ],',
      '                  ),',
      '                  const SizedBox(height: 24),',
      '                  Row(',
      '                    children: [',
      '                      Expanded(',
      '                        child: _buildPointAction(',
      '                          icon: Icons.qr_code_scanner,',
      "                          label: '포인트 적립',",
      '                          onTap: () {',
      '                            setState(() {',
      '                              _userPoints += 10;',
      "                              _history.insert(0, PointHistoryItem(title: '출석 체크 보상', amount: 10, date: '방금 전', isEarned: true));",
      '                            });',
      '                          },',
      '                        ),',
      '                      ),',
      '                      const SizedBox(width: 12),',
      '                      Expanded(',
      '                        child: _buildPointAction(',
      '                          icon: Icons.shopping_bag_outlined,',
      "                          label: '포인트 사용',",
      '                          onTap: () {',
      '                            Navigator.pushReplacement(',
      '                              context,',
      '                              MaterialPageRoute(builder: (context) => const StoreScreen()),',
      '                            );',
      '                          },',
      '                        ),',
      '                      ),',
      '                    ],',
      '                  ),',
      '                ],',
      '              ),',
      '            ),',
      '            const SizedBox(height: 32),',
      '            Row(',
      '              mainAxisAlignment: MainAxisAlignment.spaceBetween,',
      '              children: [',
      "                const Text('포인트 내역', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),",
      '                TextButton(',
      '                  onPressed: _showPointPolicyDialog,',
      "                  child: const Text('정책 안내', style: TextStyle(color: Colors.white38, fontSize: 12)),",
      '                ),',
      '              ],',
      '            ),',
      '            const SizedBox(height: 16),',
      '            ListView.separated(',
      '              shrinkWrap: true,',
      '              physics: const NeverScrollableScrollPhysics(),',
      '              itemCount: _history.length,',
      '              separatorBuilder: (context, index) => Divider(color: Colors.white.withOpacity(0.05), height: 1),',
      '              itemBuilder: (context, index) {',
      '                final item = _history[index];',
      '                return Padding(',
      '                  padding: const EdgeInsets.symmetric(vertical: 16),',
      '                  child: Row(',
      '                    children: [',
      '                      Container(',
      '                        padding: const EdgeInsets.all(10),',
      '                        decoration: BoxDecoration(',
      '                          color: (item.isEarned ? Colors.cyanAccent : Colors.orangeAccent).withOpacity(0.1),',
      '                          shape: BoxShape.circle,',
      '                        ),',
      '                        child: Icon(',
      '                          item.isEarned ? Icons.add : Icons.remove,',
      '                          color: item.isEarned ? Colors.cyanAccent : Colors.orangeAccent,',
      '                          size: 16,',
      '                        ),',
      '                      ),',
      '                      const SizedBox(width: 16),',
      '                      Expanded(',
      '                        child: Column(',
      '                          crossAxisAlignment: CrossAxisAlignment.start,',
      '                          children: [',
      '                            Text(item.title, style: const TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w500)),',
      '                            const SizedBox(height: 4),',
      '                            Text(item.date, style: TextStyle(color: Colors.white.withOpacity(0.3), fontSize: 12)),',
      '                          ],',
      '                        ),',
      '                      ),',
      '                      Text(',
      "                        '\${item.isEarned ? '+' : '-'}\${item.amount} P',",
      '                        style: TextStyle(',
      '                          color: item.isEarned ? Colors.cyanAccent : Colors.white70,',
      '                          fontSize: 15,',
      '                          fontWeight: FontWeight.bold,',
      '                        ),',
      '                      ),',
      '                    ],',
      '                  ),',
      '                );',
      '              },',
      '            ),',
      '          ],',
      '        ),',
      '      ),',
      '      bottomNavigationBar: _buildBottomFixedUI(),',
      '    );',
      '  }',
      '',
      '  Widget _buildPointAction({required IconData icon, required String label, required VoidCallback onTap}) {',
      '    return GestureDetector(',
      '      onTap: onTap,',
      '      child: Container(',
      '        padding: const EdgeInsets.symmetric(vertical: 12),',
      '        decoration: BoxDecoration(',
      '          color: Colors.white.withOpacity(0.05),',
      '          borderRadius: BorderRadius.circular(16),',
      '        ),',
      '        child: Row(',
      '          mainAxisAlignment: MainAxisAlignment.center,',
      '          children: [',
      '            Icon(icon, color: Colors.white, size: 18),',
      '            const SizedBox(width: 8),',
      '            Text(label, style: const TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.w500)),',
      '          ],',
      '        ),',
      '      ),',
      '    );',
      '  }',
      '',
      '  void _showPointPolicyDialog() {',
      '    showDialog(',
      '      context: context,',
      '      builder: (context) => AlertDialog(',
      '        backgroundColor: const Color(0xFF1C1C1C),',
      '        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),',
      "        title: const Text('포인트 유효기간 및 자동 소멸 정책 안내', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.bold)),",
      '        content: const SingleChildScrollView(',
      '          child: Column(',
      '            mainAxisSize: MainAxisSize.min,',
      '            crossAxisAlignment: CrossAxisAlignment.start,',
      '            children: [',
      '              Text(',
      "                '안녕하세요. 서비스를 이용해 주시는 회원님께 감사의 말씀을 드립니다.\\n\\n' ",
      "                '회원님의 소중한 포인트 관리 및 원활한 서비스 제공을 위해 포인트 유효기간 정책을 아래와 같이 안내드립니다.\\n\\n' ",
      "                '• 유효기간: 각 포인트 적립일로부터 1년 (365일)\\n\\n' ",
      "                '• 소멸 방식: 유효기간이 경과한 포인트는 해당 일자 자정에 자동으로 소멸됩니다.\\n\\n' ",
      "                '• 사용 원칙: 먼저 적립된 포인트가 먼저 사용되는 \\'선입선출\\' 방식으로 차감됩니다.\\n\\n' ",
      "                '• 사전 안내: 포인트 소멸 30일 전과 7일 전에 앱 알림을 통해 소멸 예정 포인트를 미리 안내해 드립니다.\\n\\n' ",
      "                '소멸된 포인트는 복구가 불가능하오니, 유효기간 내에 현금전환이나 상품 구매 등으로 알뜰하게 사용하시길 바랍니다.',",
      '                style: TextStyle(color: Colors.white70, fontSize: 13, height: 1.6),',
      '              ),',
      '            ],',
      '          ),',
      '        ),',
      '        actions: [',
      '          TextButton(',
      '            onPressed: () => Navigator.pop(context),',
      "            child: const Text('확인', style: TextStyle(color: Colors.cyanAccent)),",
      '          ),',
      '        ],',
      '      ),',
      '    );',
      '  }',
      '',
      '  void _showWithdrawalDialog() {',
      '    showDialog(',
      '      context: context,',
      '      builder: (context) => AlertDialog(',
      '        backgroundColor: const Color(0xFF1C1C1C),',
      '        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),',
      '        title: const Row(',
      '          children: [',
      '            Icon(Icons.account_balance_wallet, color: Colors.cyanAccent, size: 24),',
      '            SizedBox(width: 8),',
      "            Text('출금 신청', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),",
      '          ],',
      '        ),',
      '        content: SingleChildScrollView(',
      '          child: Column(',
      '            mainAxisSize: MainAxisSize.min,',
      '            children: [',
      "              _buildStoreTextField('출금 액수 (5,000원 단위)'),",
      '              const SizedBox(height: 12),',
      "              _buildStoreTextField('은행명'),",
      '              const SizedBox(height: 12),',
      "              _buildStoreTextField('계좌번호'),",
      '              const SizedBox(height: 12),',
      "              _buildStoreTextField('예금주 성함'),",
      '              const SizedBox(height: 16),',
      '              Container(',
      '                padding: const EdgeInsets.all(12),',
      '                decoration: BoxDecoration(',
      '                  color: Colors.white.withOpacity(0.05),',
      '                  borderRadius: BorderRadius.circular(12),',
      '                ),',
      '                child: Column(',
      '                  crossAxisAlignment: CrossAxisAlignment.start,',
      '                  children: [',
      "                    const Text('[현금 출금 안내]', style: TextStyle(color: Colors.white70, fontSize: 11, fontWeight: FontWeight.bold)),",
      '                    const SizedBox(height: 6),',
      "                    _buildNoticeText('• 1회 최대 신청 금액: 30,000원'),",
      "                    _buildNoticeText('• 신청 횟수: 하루에 1회만 신청 가능합니다.'),",
      "                    _buildNoticeText('• 입금 소요 기간: 신청일로부터 영업일 기준 1~3일 이내에 입금됩니다.'),",
      '                  ],',
      '                ),',
      '              ),',
      '              const SizedBox(height: 20),',
      '              SizedBox(',
      '                width: double.infinity,',
      '                height: 50,',
      '                child: ElevatedButton(',
      '                  onPressed: () {',
      '                    Navigator.pop(context);',
      '                    ScaffoldMessenger.of(context).showSnackBar(',
      "                      const SnackBar(content: Text('출금 신청이 완료되었습니다.'), behavior: SnackBarBehavior.floating),",
      '                    );',
      '                  },',
      '                  style: ElevatedButton.styleFrom(',
      '                    backgroundColor: Colors.cyanAccent,',
      '                    foregroundColor: Colors.black,',
      '                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),',
      '                  ),',
      "                  child: const Text('출금 신청하기', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),",
      '                ),',
      '              ),',
      '            ],',
      '          ),',
      '        ),',
      '      ),',
      '    );',
      '  }',
      '',
      '  Widget _buildStoreTextField(String label) {',
      '    return TextField(',
      '      style: const TextStyle(color: Colors.white),',
      '      decoration: InputDecoration(',
      '        labelText: label,',
      '        labelStyle: const TextStyle(color: Colors.white38, fontSize: 13),',
      '        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide(color: Colors.white.withOpacity(0.1))),',
      '        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Colors.cyanAccent)),',
      '        filled: true,',
      '        fillColor: Colors.white.withOpacity(0.02),',
      '      ),',
      '    );',
      '  }',
      '',
      '  Widget _buildNoticeText(String text) {',
      '    return Padding(',
      '      padding: const EdgeInsets.only(bottom: 4),',
      '      child: Text(text, style: TextStyle(color: Colors.white.withOpacity(0.5), fontSize: 11, height: 1.4)),',
      '    );',
      '  }',
      '',
      '  Widget _buildBottomFixedUI() {',
      '    final bottomPadding = MediaQuery.of(context).padding.bottom;',
      '    return Align(',
      '      alignment: Alignment.bottomCenter,',
      '      child: Padding(',
      '        padding: EdgeInsets.only(bottom: bottomPadding + 10.0, left: 32.0, right: 32.0),',
      '        child: Container(',
      '          height: 64,',
      '          decoration: BoxDecoration(',
      '            color: const Color(0xFF1C1C1C).withOpacity(0.95),',
      '            borderRadius: BorderRadius.circular(32),',
      '            boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.4), blurRadius: 20, spreadRadius: 5)],',
      '            border: Border.all(color: Colors.white.withOpacity(0.05)),',
      '          ),',
      '          child: Row(',
      '            mainAxisAlignment: MainAxisAlignment.spaceEvenly,',
      '            children: [',
      '              IconButton(icon: const Icon(Icons.home_filled, color: Colors.white), onPressed: () => Navigator.pop(context)),',
      '              IconButton(icon: const Icon(Icons.search, color: Colors.white54), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.add_circle, color: Colors.cyanAccent, size: 32), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.star_outline, color: Colors.white54), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.person_outline, color: Colors.white54), onPressed: () {}),',
      '            ],',
      '          ),',
      '        ),',
      '      ),',
      '    );',
      '  }',
      '}',
      ''
    ];
    lines.replaceRange(pointScreenStart, pointScreenEnd, newPointScreen);
  }

  // 2. Fix StoreScreen class (Lines 2100-2400 approx)
  int storeScreenStart = -1;
  int storeScreenEnd = -1;
  for (int i = 0; i < lines.length; i++) {
    if (lines[i].contains('class StoreScreen extends StatefulWidget')) {
      storeScreenStart = i;
    }
    if (storeScreenStart != -1 && lines[i].contains('class CategoryProductScreen extends StatelessWidget')) {
      storeScreenEnd = i;
      break;
    }
  }

  if (storeScreenStart != -1 && storeScreenEnd != -1) {
    print('Replacing StoreScreen class...');
    final newStoreScreen = [
      'class StoreScreen extends StatefulWidget {',
      '  const StoreScreen({super.key});',
      '',
      '  @override',
      '  State<StoreScreen> createState() => _StoreScreenState();',
      '}',
      '',
      'class _StoreScreenState extends State<StoreScreen> {',
      '  @override',
      '  Widget build(BuildContext context) {',
      '    return Scaffold(',
      '      backgroundColor: Colors.black,',
      '      appBar: AppBar(',
      '        backgroundColor: Colors.black,',
      '        elevation: 0,',
      '        leading: IconButton(',
      '          icon: const Icon(Icons.arrow_back_ios, color: Colors.white),',
      '          onPressed: () => Navigator.pop(context),',
      '        ),',
      "        title: const Text('포인트 스토어', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),",
      '        centerTitle: true,',
      '      ),',
      '      body: SingleChildScrollView(',
      '        padding: const EdgeInsets.all(20),',
      '        child: Column(',
      '          crossAxisAlignment: CrossAxisAlignment.start,',
      '          children: [',
      '            Container(',
      '              width: double.infinity,',
      '              padding: const EdgeInsets.all(20),',
      '              decoration: BoxDecoration(',
      '                color: const Color(0xFF1C1C1C),',
      '                borderRadius: BorderRadius.circular(20),',
      '                border: Border.all(color: Colors.cyanAccent.withOpacity(0.3)),',
      '              ),',
      '              child: Row(',
      '                children: [',
      '                  const Icon(Icons.stars, color: Colors.cyanAccent, size: 24),',
      '                  const SizedBox(width: 12),',
      '                  Expanded(',
      '                    child: Column(',
      '                      crossAxisAlignment: CrossAxisAlignment.start,',
      '                      children: [',
      "                        const Text('현금 인출하기', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),",
      '                        const SizedBox(height: 4),',
      "                        Text('보유하신 포인트를 현금으로 인출하세요', style: TextStyle(color: Colors.white.withOpacity(0.5), fontSize: 12)),",
      '                      ],',
      '                    ),',
      '                  ),',
      '                  ElevatedButton(',
      '                    onPressed: _showWithdrawalDialog,',
      '                    style: ElevatedButton.styleFrom(',
      '                      backgroundColor: Colors.cyanAccent,',
      '                      foregroundColor: Colors.black,',
      '                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),',
      '                      padding: const EdgeInsets.symmetric(horizontal: 16),',
      '                    ),',
      "                    child: const Text('인출신청', style: TextStyle(fontWeight: FontWeight.bold)),",
      '                  ),',
      '                ],',
      '              ),',
      '            ),',
      '            const SizedBox(height: 30),',
      "            const Text('카테고리', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold)),",
      '            const SizedBox(height: 16),',
      '            GridView.count(',
      '              shrinkWrap: true,',
      '              physics: const NeverScrollableScrollPhysics(),',
      '              crossAxisCount: 4,',
      '              mainAxisSpacing: 20,',
      '              crossAxisSpacing: 10,',
      '              children: [',
      "                _buildCategoryItem(Icons.coffee, '커피'),",
      "                _buildCategoryItem(Icons.fastfood, '편의점'),",
      "                _buildCategoryItem(Icons.card_giftcard, '상품권'),",
      "                _buildCategoryItem(Icons.restaurant, '외식'),",
      "                _buildCategoryItem(Icons.shopping_bag, '백화점'),",
      "                _buildCategoryItem(Icons.movie, '영화'),",
      "                _buildCategoryItem(Icons.cake, '베이커리'),",
      "                _buildCategoryItem(Icons.more_horiz, '기타'),",
      '              ],',
      '            ),',
      '          ],',
      '        ),',
      '      ),',
      '      bottomNavigationBar: _buildBottomFixedUI(),',
      '    );',
      '  }',
      '',
      '  Widget _buildCategoryItem(IconData icon, String label) {',
      '    return GestureDetector(',
      '      onTap: () {',
      '        Navigator.push(',
      '          context,',
      '          MaterialPageRoute(builder: (context) => CategoryProductScreen(categoryName: label)),',
      '        );',
      '      },',
      '      child: Column(',
      '        children: [',
      '          Container(',
      '            padding: const EdgeInsets.all(12),',
      '            decoration: BoxDecoration(',
      '              color: const Color(0xFF1C1C1C),',
      '              borderRadius: BorderRadius.circular(15),',
      '            ),',
      '            child: Icon(icon, color: Colors.white, size: 24),',
      '          ),',
      '          const SizedBox(height: 8),',
      "          Text(label, style: const TextStyle(color: Colors.white70, fontSize: 12)),",
      '        ],',
      '      ),',
      '    );',
      '  }',
      '',
      '  void _showWithdrawalDialog() {',
      '    showDialog(',
      '      context: context,',
      '      builder: (context) => AlertDialog(',
      '        backgroundColor: const Color(0xFF1C1C1C),',
      '        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),',
      "        title: const Text('현금 인출 신청', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),",
      '        content: Column(',
      '          mainAxisSize: MainAxisSize.min,',
      '          children: [',
      "            _buildStoreTextField('인출할 포인트 (5,000 P 단위)'),",
      '            const SizedBox(height: 12),',
      "            _buildStoreTextField('입금받으실 계좌번호'),",
      '            const SizedBox(height: 12),',
      "            _buildStoreTextField('은행명 및 예금주'),",
      '          ],',
      '        ),',
      '        actions: [',
      '          TextButton(onPressed: () => Navigator.pop(context), child: const Text("취소")),',
      '          ElevatedButton(',
      '            onPressed: () => Navigator.pop(context),',
      '            style: ElevatedButton.styleFrom(backgroundColor: Colors.cyanAccent, foregroundColor: Colors.black),',
      "            child: const Text('신청하기'),",
      '          ),',
      '        ],',
      '      ),',
      '    );',
      '  }',
      '',
      '  Widget _buildStoreTextField(String label) {',
      '    return TextField(',
      '      style: const TextStyle(color: Colors.white),',
      '      decoration: InputDecoration(',
      '        labelText: label,',
      '        labelStyle: const TextStyle(color: Colors.white38, fontSize: 12),',
      '        enabledBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.white.withOpacity(0.1))),',
      '        focusedBorder: const UnderlineInputBorder(borderSide: BorderSide(color: Colors.cyanAccent)),',
      '      ),',
      '    );',
      '  }',
      '',
      '  Widget _buildBottomFixedUI() {',
      '    final bottomPadding = MediaQuery.of(context).padding.bottom;',
      '    return Align(',
      '      alignment: Alignment.bottomCenter,',
      '      child: Padding(',
      '        padding: EdgeInsets.only(bottom: bottomPadding + 10.0, left: 32.0, right: 32.0),',
      '        child: Container(',
      '          height: 64,',
      '          decoration: BoxDecoration(',
      '            color: const Color(0xFF1C1C1C).withOpacity(0.95),',
      '            borderRadius: BorderRadius.circular(32),',
      '            boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.4), blurRadius: 20, spreadRadius: 5)],',
      '            border: Border.all(color: Colors.white.withOpacity(0.05)),',
      '          ),',
      '          child: Row(',
      '            mainAxisAlignment: MainAxisAlignment.spaceEvenly,',
      '            children: [',
      '              IconButton(icon: const Icon(Icons.home_filled, color: Colors.white), onPressed: () => Navigator.pop(context)),',
      '              IconButton(icon: const Icon(Icons.search, color: Colors.white54), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.add_circle, color: Colors.cyanAccent, size: 32), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.star_outline, color: Colors.white54), onPressed: () {}),',
      '              IconButton(icon: const Icon(Icons.person_outline, color: Colors.white54), onPressed: () {}),',
      '            ],',
      '          ),',
      '        ),',
      '      ),',
      '    );',
      '  }',
      '}',
      ''
    ];
    lines.replaceRange(storeScreenStart, storeScreenEnd, newStoreScreen);
  }

  // Save the file
  file.writeAsStringSync(lines.join('\n'));
  print('MEGA FIX complete.');
}
